import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import Modal from "./components/Modal/Modal";
import Navigation from "./components/Navigation/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Virtual wallet",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {

  return (
    <html lang="en">
      <body className={`${inter.className} flex`} >
        <Navigation />
        <main className="py-8 px-5 w-4/5 my-0 mx-auto felx-1 h-screen">{children}</main>
        <Suspense fallback={<>Loading...</>}>
          <Modal />
        </Suspense>
      </body>
    </html>
  );
}
