import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar/Sidebar";
import Modal from "./components/Modal/Modal";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Virtual wallet",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {

  return (
    <html lang="en">
      <body className={inter.className} >
        <Sidebar />
        <section className="root_section">{children}</section>
        <Suspense fallback={<>Loading...</>}>
          <Modal />
        </Suspense>
      </body>
    </html>
  );
}
