import type { Metadata } from "next";

import "./globals.css";
import { ReactNode } from "react";
import { Inter } from "next/font/google";
import Provider from "./components/Provider/Provider";
import Navigation from "./components/Sidebar/Sidebar";
import { getServerSession } from "next-auth";
import { FraudulentTransactionsProvider } from "@/hooks/useFraudulentContext/FraudulentTransactionsContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Virtual wallet",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: ReactNode;
};

const RootLayout = async ({ children }: RootLayoutProps) => {
  const session = await getServerSession();

  return (
    <html lang="en">
      {session ? (
        <body className={`${inter.className} flex`}>
          <Provider>
            <FraudulentTransactionsProvider>
              <Navigation />
              <main className="py-20 px-28 w-4/5 my-0 mx-auto h-screen">
                {children}
              </main>
            </FraudulentTransactionsProvider>
          </Provider>
        </body>
      ) : (
        <body className={`${inter.className} flex bg-logged custombackground`}>
          <Provider>
            <main className="w-screen h-screen">
              {children}
            </main>
          </Provider>
        </body>
      )}
    </html>
  );
};

export default RootLayout;
